version: "3.9"

services:
  server:
    build: .
    volumes:
      - .:/app  # Mount the current directory (backend) to /app inside the container
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://postgres:Ak%40123@db:5432/dream11
    depends_on:
      - db
  db:
    image: docker.io/postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: Ak@123
      POSTGRES_DB: dream11
    ports:
      - 5432:5432
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
  
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000


