version: "3.9"

services:
  db:
    image: docker.io/postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: Ak@123
      POSTGRES_DB: dream11
    ports:
      - 5432:5432
    volumes:
      - ./pgdata/:/var/lib/postgresql/data

